# Generated by Django 4.2.10 on 2024-02-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='tahun_terbit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ulasan',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
