# Generated by Django 4.2.10 on 2024-02-21 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_buku_tahun_terbit_alter_ulasan_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.kategori'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Kategori_Buku',
        ),
    ]
