# Generated by Django 4.2.10 on 2024-02-21 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_buku_kategori_delete_kategori_buku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='kategori',
        ),
        migrations.CreateModel(
            name='Kategori_Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buku')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kategori')),
            ],
        ),
    ]
