# Generated by Django 4.2.10 on 2024-02-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_buku_kategori_kategori_buku'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='kategori',
            field=models.ManyToManyField(to='app.kategori'),
        ),
    ]
