# Generated by Django 4.2.10 on 2024-02-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_buku_kategori'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kategori_Buku',
        ),
    ]
