# Generated by Django 4.2.10 on 2024-02-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_kategori_buku'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjam',
            name='status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
