# Generated by Django 4.2.10 on 2024-02-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pinjam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='tanggal_peminjaman',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pinjam',
            name='tanggal_pengembalian',
            field=models.DateTimeField(),
        ),
    ]
